### ISSUE TITLE
ML-KEM private keys not compatible with draft-ietf-lamps-kyber-certificates-06 (seed as private key)

### ISSUE THREAD

**Issue by tomato42** [open-quantum-safe/oqs-provider#613]
**Describe the bug**
The private key files generated using oqsprovider do not follow the ~[draft-ietf-lamps-cms-kyber-07](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-cms-kyber-07)~ [draft-ietf-lamps-kyber-certificates-06](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-kyber-certificates-06) standard. More specifically, the saved private key is not the seed used to generate it but the expanded value.

**To Reproduce**
Steps to reproduce the behaviour:
1. `openssl genpkey -out private-key.pem -algorithm mlkem512`
2. inspect private-key.pem

**Expected behavior**
The file should be small, just two lines of base64 encoded data. Instead the file is over 4kiB large.

**Environment (please complete the following information):**
 - OS: RHEL-10
 - OpenSSL version: openssl-3.2.2-14.el10
 - oqsprovider version: oqsprovider-0.8.0-2.el10.

Please run the following commands to obtain the version information:
 - For OpenSSL: `openssl version` :
   ```
   OpenSSL 3.2.2 4 Jun 2024 (Library: OpenSSL 3.2.2 4 Jun 2024)
   ```
 - For oqsprovider: `openssl list -providers`:
   ```
   Providers:
     default
       name: OpenSSL Default Provider
       version: 3.2.2
       status: active
     oqsprovider
       name: OpenSSL OQS Provider
       version: 0.8.0
       status: active
   ```
