### ISSUE TITLE
Set the quantum-safe KEM algorithm through "groups"

### ISSUE THREAD

**Issue by yxungh** [open-quantum-safe/oqs-provider#627]
I need to use OpenSSL 3.0.3 for some reasons and use oqs-provider at the same time.
```
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.3
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.8.1-dev
    status: active
```

I incorporated this part of the code into OpenSSL 3.0.3. 
  https://github.com/openssl/openssl/pull/19312

After that, I can establish a TLS 1.3 connection using the Falcon512 certificate.
Does the modified OpenSSL 3.0.3 support all the functions of OQS?@baentsch

 However, when I set the "groups", the handshake fails.

`SSL_connect failed: error:0A000410:SSL routines::sslv3 alert handshake failure`

Set in the client
```
    ssl = SSL_new(ctx);
    SSL_set_fd(ssl, sockfd);
    SSL_set1_groups_list(ssl, "frodo640shake");
```
